# Generated by Django 3.0.3 on 2020-08-20 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_remove_wishlist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
