# Generated by Django 3.0.3 on 2020-08-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_auto_20200820_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddingMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_add', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_crew',
            field=models.CharField(default='Not Available', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_location',
            field=models.CharField(default='Not Available', max_length=120),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_votes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
