# Generated by Django 3.0.3 on 2020-08-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_auto_20200822_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
